### ISSUE TITLE
Do the uploading ourselves for textract so we can avoid repeated uploads

### ISSUE THREAD

**Issue by eric-anderson** [aryn-ai/sycamore#173]
The textract uploading support uses the default textract code which uploads the file under a guid from scratch each time. It would be better to upload the file under a content based hash so that we can avoid repeated uploads and storage of the same data.

Potentially the implementation here interacts with the way we could cache textract results in 
https://github.com/aryn-ai/quickstart/issues/3

**Comment by HenryL27** [comment]
can we close this now that we have caching?

**Comment by eric-anderson** [comment]
We have caching and we're moving away from using textract to the aryn partitioner.
