### ISSUE TITLE
Augmenting text representation with metadata

### ISSUE THREAD

**Issue by HenryL27** [aryn-ai/sycamore#206]
**Is your feature request related to a problem? Please describe.**
A lot of the time the actual text representation of a chunk will not include enough information to generate a useful embedding or perform adequate keyword search queries. Including some of the metadata that has been extracted in earlier pipeline steps as part of the text representation for the chunk can greatly increase performance. e.g.:
```
document {
  text_representation: "maintenance procedure: step 1. [blah] step 2. [blah] step 3. [blah]",
  properties {
    part_name: "zebulon fork A3"
  }
}
```
Let's provide a way to include the part name in the text, e.g.:
```
document {
  text_representation: "this pertains to the part "zebulon fork A3". maintenance procedure: step 1. [blah] step 2. [blah] step 3. [blah]",
  properties {
    part_name: "zebulon fork A3"
  }
}
```

**Describe the solution you'd like**
Implement a transform `augment_text` that takes a list of format strings. Replace the text representation of each document by formatting and joining the format strings. We take a list of such fmt strings because some documents may be missing certain properties, and so rather than voiding the entire operation in that case, we can simply drop the segment that's missing a value. Likely the original `text_representation` should be the final element, but I don't think that's a requirement. My recommendation is an API like so:
```
docset.augment_text([
    "This pertains to the part {doc.properties['part_name']}.",
    "{doc.text_representation}"
])
```

**Describe alternatives you've considered**
**Alt 1.**
```
docset.augment_text(prefix = ["This pertains to the part {doc.properties['part_name']}."], include_original_text=True, suffix=[])
```
This acts the same way, but treats the `text_representation` specially. I think it's unnecessarily messy though.
**Alt 2.**
Pass in a single format string
```
docset.augment_text("This pertains to the part {doc.properties['part_name']}. {doc.text_representation}")
```
If a document doesn't have a part name, this will cause problems. I mean, in this case it might work out ok but due to the error handling simply leaving the text_representation as it is, which would probably be intended, but in cases with more complicated augmentations I don't think the partial failure mode should be "do nothing"
**Alt 3**
Pass in a function
```
docset.augment_text(lambda doc: f"This pertains to the part {doc.properties['part_name'}. {doc.text_representation}")
```
This lets the user control exactly what happens - they just have to provide a function that takes a document and spits out a string. In the example I've done something simple, but this could be arbitrarily complex. But if we're going with this route, then the user might as well just use `docset.map()`, because the body of augment_text would just be something like
```
def augment_text(self, fn):
    def f(doc):
        doc.text_representation = fn(doc)
        return doc
    self.map(f)
```
**Alt 4**
Do nothing and just recommend people use `map` as in Alt 3. I feel like this is a feature we want directly exposed in the API though.
**Alt 5**
Alt 2, but you give it a list of format strings to fall back to. e.g.
```
docset.augment_text(["This pertains to the part {doc.properties['part_name']}. {doc.text_representation}", "There is not part name for this document. {doc.text_representation}"])
```
I just think this is extremely clunky.

**Additional context**
One interesting nuance to all this is that we're likely adding a whole bunch of tokens to the text representation, meaning that we're also likely to overflow the embedding models' context window if we're not careful. I'm not really sure what can be done to mitigate this other than just manually tuning the segmentation since the partitioning happens first and the number of tokens we're adding is a little random. Additionally, adding splitting steps after the text augmentation brings us right back to the place from which this augmentation came from. Maybe further down the line we can augment augmentation to also take in a splitter or something so it can dynamically calculate how many tokens it will add to a document and then split if it needs to. But doing something like this would be an argument for Alternative 1.

**Comment by baitsguy** [comment]
I like how simple the proposed solution is, but do we also want to follow the pattern of existing transforms where we pass in the actual execution class (some Augmentor.class)

**Comment by HenryL27** [comment]
right, yes, that's how we do things. Simple enough to wrap like this

**Comment by bsowell** [comment]
If you have a list of options, how do you determine which properties each option are present/necessary? Do you just try to format the string and catch KeyErrors? 

Other question is whether this should be at the Document or Element level? I guess it just depends on whether we expect people to call `explode` first.

**Comment by HenryL27** [comment]
yep, currently using try/catch. There doesn't seem to be a great way to get the requested replacement vars other than simply parsing it myself - which maybe I should just do.

starting at the Document level. But element level might make more sense. My thinking was that this is something you do to improve embeddings so it should be near that - and so after explode. But it also seems a bit like an element transform since it screws with the text_rep
