### ISSUE TITLE
Cannot run unit tests according to CONTRIBUTING.md

### ISSUE THREAD

**Issue by hsm207** [aryn-ai/sycamore#364]
**Describe the bug**
Running `poetry run pytest sycamore/tests/unit/` from the project root folder throws:

> ERROR: file or directory not found: sycamore/tests/unit/

**To Reproduce**
1. Go to the project's root directory
2. Run `poetry run pytest sycamore/tests/unit/`
3. See error

**Expected behavior**
Unit tests are run

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 12 (bookworm)
 - Browser [e.g. chrome, safari]: NA
 - Version [e.g. 22]: NA

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser: NA
 - Version: NA

**Additional context**
I am following the instructions in [Developer Setup](https://github.com/aryn-ai/sycamore/blob/8a239f54358be580e2b3be259872ad0769c6e4b3/CONTRIBUTING.md#L27) in CONTRIBUTING.md guide

**Comment by bsowell** [comment]
Ahh, thanks for pointing this out. We did a refactor recently and didn't update the CONTRIBUTING instructions accordingly. The library portion of sycamore has moved to lib/sycamore, so you should be able to run the tests from inside that directory. 

Let me do a rev on the instructions and get a PR out today.

**Comment by bsowell** [comment]
@hsm207 Thanks so much for looking at sycamore! Please feel free to reach out if there is anything else we can do to help!

**Comment by HenryL27** [comment]
Updated the instructions to `poetry run lib/sycamore/sycamore/tests/unit/`, which should be correct
