### ISSUE TITLE
MetadataDocument constructor should call super constructor with **kwargs

### ISSUE THREAD

**Issue by rbpasker** [aryn-ai/sycamore#597]
should be 

`        super().__init__(document, **kwargs)`

https://github.com/aryn-ai/sycamore/blob/b4fc331e82ed5a7f693945d6b5e294c95ccbd98d/lib/sycamore/sycamore/data/document.py#L218

**Comment by eric-anderson** [comment]
I don't think we want that. If we pass through the kwargs they will end up in the [userdict](https://github.com/aryn-ai/sycamore/blob/f027cc1d511bdbed1ee514821e2371212def0267/lib/sycamore/sycamore/data/document.py#L24), but for a metadata document we want the [kwargs to end up in metadata](https://github.com/aryn-ai/sycamore/blob/f027cc1d511bdbed1ee514821e2371212def0267/lib/sycamore/sycamore/data/document.py#L221).

**Comment by eric-anderson** [comment]
What are you wanting kwargs in Metadata for?

**Comment by rbpasker** [comment]
you're right
