### ISSUE TITLE
ImportError: cannot import name 'ArynPartitioner' from 'sycamore.transforms.partition'

### ISSUE THREAD

**Issue by rroy0412** [aryn-ai/sycamore#744]
Not able to import ArynPartitioner

**Comment by HenryL27** [comment]
What's your sycamore version? python version?

**Comment by rroy0412** [comment]
sycamore-ai --> Version: 0.1.17
Python: 3.10.14

**Comment by HenryL27** [comment]
I think `ArynPartitioner` was released in 0.1.18 - we're up to 0.1.19 now tho so I'd go for that.
`sycamore` is an independent python package that has nothing to do with us, so I wouldn't be too surprised if installing sycamore-ai and then syacmore leads to weird behavior trying to import stuff.

**Comment by HenryL27** [comment]
did upgrading sycamore-ai and uninstalling sycamore fix the issue?

**Comment by rroy0412** [comment]
yes, it worked with latest version. Thank you.
